name : create meeting report
on:
  schedule:
    - cron:  '0 7 * * 5' #   Test. In general, create at 8 am on Friday (0 7 * * 5)
#on:
#  push:
#    branches:
#      - master
jobs:
  get_repo:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps :
      - name: echo test
        run: |
          echo "start test"
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: 3.11
      - name: do action checkout
        uses: actions/checkout@v3
      - name: get github repository
        env:
          SECRET2: ${{ secrets.SECRET2 }}
        run: |
          if [ -z "$SECRET2" ]; then echo "SECRET2 is not set!"; exit 1; else echo "SECRET2 is set!"; fi
          python -m pip install --upgrade setuptools wheel
          python -m pip install numpy==1.24.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python scripts/create_dev_meetings_report.py
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: email config
        run: | 
          git config --global user.name "Hanna Stapel"
          git config --global user.email "stapel@apc.in2p3.fr"
      - name: commit changed files
        run: git commit -m 'auto create meeting report'
      - name: push changes
        run: git push
